version: "3.9"

services:
  master:
    image: postgres:latest
    container_name: "master"
    environment:
      POSTGRES_DB: "avito-tech-local"
      POSTGRES_USER: "avito-tech-local-admin"
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    restart: unless-stopped
#    networks:
#      - mynet

  slave:
    image: postgres:latest
    container_name: "slave"
    environment:
      POSTGRES_DB: "avito-tech-local"
      POSTGRES_USER: "avito-tech-local-admin"
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5423:5432"
    restart: unless-stopped

  cache:
    image: redis
    restart: unless-stopped
    ports:
      - '6379:6379'

  pgAdmin:
    container_name: "avito_pg-admin"
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: adming@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_LISTEN_PORT: 8081
    ports:
      - 8082:8081
    restart: unless-stopped

#volumes:
#  postgres-db-master:
#  postgres-db-slave:
#
#networks:
#  mynet:
#    driver: bridge
#    ipam:
#      driver: default
#      config:
#        - subnet: 172.16.1.0/24